# Generated by Django 2.2.6 on 2020-05-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contas',
            new_name='Conta',
        ),
    ]
