# Generated by Django 2.2.6 on 2020-05-03 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20200502_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='dt_cricao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
