# Generated by Django 2.2.6 on 2020-05-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_conta_dt_cricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='dt_cricao',
            new_name='dt_criacao',
        ),
    ]
